### ISSUE TITLE
About numeric address in .json files

### ISSUE THREAD

**Issue by layahcn** [Maufeat/Waven-Translation#2]
The numbers can be replaced with real addresses to facilitate translation.
Just like this one in Achievements.json
8131 in ("8131": "Terminer le chapitre VIII",) → ACHIEVEMENT_101_NAME

[LocalizedTextData-resources.assets-146-MonoBehaviour.txt](https://github.com/Maufeat/Waven-Translation/files/6032884/LocalizedTextData-resources.assets-146-MonoBehaviour.txt)

**Comment by Maufeat** [comment]
Hello, yes this can be done. I will take a look at it and map the IDs with the stringed IDs.
